version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: financial_api_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CACHE_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - api_network

volumes:
  redis_data:
    driver: local

networks:
  api_network:
    driver: bridge 